default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# development:
#   <<: *default
#   adapter: sqlite3
#   database: db/development.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: twittor
  username: app_postgres
  password: <%= ENV['APP_POSTGRES_DATABASE_PASSWORD'] %>
